"use client";

import { useState } from "react";
import { api, Playbook, Recommendation } from "@/lib/api";
import { useQuery } from "@/lib/useQuery";
import Markdown from "./Markdown";
import { Skeleton } from "./states";
import { SparkIcon } from "./icons";

/**
 * The "Execute" action under the recommendations list.
 *
 * One button rather than one per recommendation: the weakest habits are almost
 * always facets of a single underlying one (not showing concrete evidence), so
 * a combined playbook teaches the habit instead of five disconnected rules.
 *
 * This is the only place in the product that calls a language model, and the
 * UI says so — every number it is given was measured locally first.
 */
export default function ExecutePanel({
  recommendations,
  path,
}: {
  recommendations: Recommendation[];
  path?: string;
}) {
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<Playbook | null>(null);
  const [error, setError] = useState<string | null>(null);

  // An existing playbook loads for free; generating one costs an API call.
  const stored = useQuery<Playbook>(
    path ? `playbook:${path}` : null,
    () => api.playbook(path),
    { staleMs: 300_000 },
  );

  const playbook = result ?? (stored.data?.exists ? stored.data : null);
  const llmAvailable = stored.data?.llm_available ?? false;

  async function generate(force = false) {
    setGenerating(true);
    setError(null);
    try {
      setResult(await api.generatePlaybook(path, force));
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="card mt-2 p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="min-w-0">
          <h3 className="text-sm font-medium">
            Turn these {recommendations.length} habits into a playbook
          </h3>
          <p className="mt-0.5 text-2xs text-content-subtle">
            Rewrites your own low-scoring prompts to fix all of them at once.
            {!llmAvailable && " Requires ANTHROPIC_API_KEY."}
          </p>
        </div>

        <button
          onClick={() => generate(Boolean(playbook))}
          disabled={generating || !llmAvailable}
          title={
            llmAvailable
              ? undefined
              : "Set ANTHROPIC_API_KEY in your environment and restart the backend"
          }
          className="inline-flex h-11 shrink-0 items-center gap-1.5 rounded-md bg-accent px-4
                     text-sm font-medium text-canvas transition-colors duration-200 ease-expo
                     hover:bg-accent-hover disabled:cursor-not-allowed disabled:opacity-40"
        >
          <SparkIcon width={14} height={14} className={generating ? "animate-spin" : ""} />
          {generating ? "Generating…" : playbook ? "Regenerate" : "Execute"}
        </button>
      </div>

      {generating && (
        <div className="mt-4 space-y-2">
          <Skeleton className="h-3 w-1/3" />
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-5/6" />
          <Skeleton className="h-3 w-2/3" />
        </div>
      )}

      {error && !generating && (
        <p className="mt-3 text-sm text-score-low">
          {/^5\d\d|auth|api_key/i.test(error)
            ? "Couldn't reach the Claude API. Set ANTHROPIC_API_KEY and restart the backend."
            : error}
        </p>
      )}

      {playbook?.markdown && !generating && (
        <div className="mt-4 border-t border-line pt-3">
          {playbook.stale && (
            <p className="mb-2 rounded bg-score-mid/10 px-2 py-1 text-2xs text-score-mid">
              Written before your latest prompts — regenerate for current advice.
            </p>
          )}
          <Markdown>{playbook.markdown}</Markdown>
          <p className="mt-4 border-t border-line pt-2 text-2xs text-content-faint">
            Generated by Claude from your measured weaknesses. Scores, percentages
            and signals are all computed locally — the model only writes the prose.
          </p>
        </div>
      )}
    </div>
  );
}
