"""Tell real user prompts apart from transcript noise.

Claude Code's session log records every user-role turn, but many of those turns
were never typed by a person: skill files injected into context, slash-command
echoes, IDE file-open events, task notifications, compaction notices. Scoring
them is worse than useless — they are long and well-structured, so they score
*highly* and crowd out the user's actual prompts in "best prompt" rankings.

Two jobs here:

  1. ``classify`` labels a turn so reports can exclude non-prompts.
  2. ``clean`` strips wrapper blocks that surround an otherwise real prompt, so
     the scorer sees the words the user actually wrote rather than XML noise
     that skews clarity and specificity.
"""
from __future__ import annotations

import re

KIND_USER = "user"
KIND_SKILL = "skill_injection"
KIND_COMMAND = "slash_command"
KIND_SYSTEM = "system_notice"
KIND_IDE = "ide_event"
KIND_EMPTY = "empty"

# Wrapper blocks that may surround a genuine prompt. Removed before scoring.
_STRIP_BLOCKS = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<ide_selection>.*?</ide_selection>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<ide_opened_file>.*?</ide_opened_file>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<task-notification>.*?</task-notification>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<local-command-caveat>.*?</local-command-caveat>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.DOTALL | re.IGNORECASE),
    re.compile(r"<command-(name|message|args)>.*?</command-(name|message|args)>", re.DOTALL | re.IGNORECASE),
]

# A turn is noise when, after stripping, it still opens with one of these.
_NOISE_PREFIXES: list[tuple[re.Pattern, str]] = [
    (re.compile(r"^Base directory for this skill:", re.IGNORECASE), KIND_SKILL),
    (re.compile(r"^\[Request interrupted", re.IGNORECASE), KIND_SYSTEM),
    (re.compile(r"^Caveat: The messages below were generated by the user", re.IGNORECASE), KIND_COMMAND),
    (re.compile(r"^This session is being continued from a previous", re.IGNORECASE), KIND_SYSTEM),
    (re.compile(r"^\[SYSTEM NOTIFICATION", re.IGNORECASE), KIND_SYSTEM),
    (re.compile(r"^API Error", re.IGNORECASE), KIND_SYSTEM),
    (re.compile(r"^<user-prompt-submit-hook>", re.IGNORECASE), KIND_SYSTEM),
]

# Whole-turn markers: if present anywhere, the turn is that kind.
_CONTAINS = [
    (re.compile(r"</?command-name>", re.IGNORECASE), KIND_COMMAND),
    (re.compile(r"</?local-command-stdout>", re.IGNORECASE), KIND_COMMAND),
    (re.compile(r"</?task-notification>", re.IGNORECASE), KIND_SYSTEM),
]

# Text left over after stripping that carries no instruction.
_TRIVIAL = re.compile(r"^(continue|resume|go on|proceed|ok|okay|yes|no|y|n|\W*)$", re.IGNORECASE)


def clean(raw: str | None) -> str:
    """Remove wrapper blocks, returning the user's own words."""
    text = raw or ""
    for pattern in _STRIP_BLOCKS:
        text = pattern.sub(" ", text)
    return text.strip()


def classify(raw: str | None) -> str:
    """Label a turn. Only KIND_USER should be scored or reported."""
    original = (raw or "").strip()
    if not original:
        return KIND_EMPTY

    for pattern, kind in _CONTAINS:
        if pattern.search(original):
            return kind

    cleaned = clean(original)
    if not cleaned:
        # The turn was nothing but wrapper blocks.
        return KIND_IDE if "<ide_" in original.lower() else KIND_SYSTEM

    for pattern, kind in _NOISE_PREFIXES:
        if pattern.match(cleaned):
            return kind

    if _TRIVIAL.match(cleaned):
        return KIND_EMPTY

    return KIND_USER


def is_user_prompt(raw: str | None) -> bool:
    return classify(raw) == KIND_USER
